// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetPay.Data;

#nullable disable

namespace NetPay.Migrations
{
    [DbContext(typeof(NetPayContext))]
    partial class NetPayContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NetPay.Data.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("NetPay.Data.Models.Household", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("NetPay.Data.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ServiceName = "Electricity"
                        },
                        new
                        {
                            Id = 2,
                            ServiceName = "Water"
                        },
                        new
                        {
                            Id = 3,
                            ServiceName = "Internet"
                        },
                        new
                        {
                            Id = 4,
                            ServiceName = "TV"
                        },
                        new
                        {
                            Id = 5,
                            ServiceName = "Phone"
                        },
                        new
                        {
                            Id = 6,
                            ServiceName = "Security"
                        },
                        new
                        {
                            Id = 7,
                            ServiceName = "Gas"
                        });
                });

            modelBuilder.Entity("NetPay.Data.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SupplierName = "E-Service"
                        },
                        new
                        {
                            Id = 2,
                            SupplierName = "Light"
                        },
                        new
                        {
                            Id = 3,
                            SupplierName = "Energy-PRO"
                        },
                        new
                        {
                            Id = 4,
                            SupplierName = "ZEC"
                        },
                        new
                        {
                            Id = 5,
                            SupplierName = "Cellular"
                        },
                        new
                        {
                            Id = 6,
                            SupplierName = "A2one"
                        },
                        new
                        {
                            Id = 7,
                            SupplierName = "Telecom"
                        },
                        new
                        {
                            Id = 8,
                            SupplierName = "Cell2U"
                        },
                        new
                        {
                            Id = 9,
                            SupplierName = "DigiTV"
                        },
                        new
                        {
                            Id = 10,
                            SupplierName = "NetCom"
                        },
                        new
                        {
                            Id = 11,
                            SupplierName = "Net1"
                        },
                        new
                        {
                            Id = 12,
                            SupplierName = "MaxTel"
                        },
                        new
                        {
                            Id = 13,
                            SupplierName = "WaterSupplyCentral"
                        },
                        new
                        {
                            Id = 14,
                            SupplierName = "WaterSupplyNorth"
                        },
                        new
                        {
                            Id = 15,
                            SupplierName = "WaterSupplySouth"
                        },
                        new
                        {
                            Id = 16,
                            SupplierName = "FiberScreen"
                        },
                        new
                        {
                            Id = 17,
                            SupplierName = "SpeedNet"
                        },
                        new
                        {
                            Id = 18,
                            SupplierName = "GasGas"
                        },
                        new
                        {
                            Id = 19,
                            SupplierName = "BlueHome"
                        },
                        new
                        {
                            Id = 20,
                            SupplierName = "SecureHouse"
                        },
                        new
                        {
                            Id = 21,
                            SupplierName = "HomeGuard"
                        },
                        new
                        {
                            Id = 22,
                            SupplierName = "SafeHome"
                        });
                });

            modelBuilder.Entity("NetPay.Data.Models.SupplierService", b =>
                {
                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("SupplierId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("SuppliersServices");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            SupplierId = 2,
                            ServiceId = 1
                        },
                        new
                        {
                            SupplierId = 3,
                            ServiceId = 1
                        },
                        new
                        {
                            SupplierId = 4,
                            ServiceId = 1
                        },
                        new
                        {
                            SupplierId = 5,
                            ServiceId = 3
                        },
                        new
                        {
                            SupplierId = 5,
                            ServiceId = 4
                        },
                        new
                        {
                            SupplierId = 5,
                            ServiceId = 5
                        },
                        new
                        {
                            SupplierId = 6,
                            ServiceId = 3
                        },
                        new
                        {
                            SupplierId = 6,
                            ServiceId = 4
                        },
                        new
                        {
                            SupplierId = 6,
                            ServiceId = 5
                        },
                        new
                        {
                            SupplierId = 6,
                            ServiceId = 6
                        },
                        new
                        {
                            SupplierId = 7,
                            ServiceId = 3
                        },
                        new
                        {
                            SupplierId = 7,
                            ServiceId = 4
                        },
                        new
                        {
                            SupplierId = 7,
                            ServiceId = 5
                        },
                        new
                        {
                            SupplierId = 8,
                            ServiceId = 3
                        },
                        new
                        {
                            SupplierId = 8,
                            ServiceId = 4
                        },
                        new
                        {
                            SupplierId = 8,
                            ServiceId = 5
                        },
                        new
                        {
                            SupplierId = 9,
                            ServiceId = 3
                        },
                        new
                        {
                            SupplierId = 9,
                            ServiceId = 4
                        },
                        new
                        {
                            SupplierId = 10,
                            ServiceId = 3
                        },
                        new
                        {
                            SupplierId = 10,
                            ServiceId = 4
                        },
                        new
                        {
                            SupplierId = 10,
                            ServiceId = 6
                        },
                        new
                        {
                            SupplierId = 11,
                            ServiceId = 3
                        },
                        new
                        {
                            SupplierId = 11,
                            ServiceId = 4
                        },
                        new
                        {
                            SupplierId = 12,
                            ServiceId = 3
                        },
                        new
                        {
                            SupplierId = 12,
                            ServiceId = 4
                        },
                        new
                        {
                            SupplierId = 12,
                            ServiceId = 5
                        },
                        new
                        {
                            SupplierId = 12,
                            ServiceId = 6
                        },
                        new
                        {
                            SupplierId = 13,
                            ServiceId = 2
                        },
                        new
                        {
                            SupplierId = 14,
                            ServiceId = 2
                        },
                        new
                        {
                            SupplierId = 15,
                            ServiceId = 2
                        },
                        new
                        {
                            SupplierId = 16,
                            ServiceId = 4
                        },
                        new
                        {
                            SupplierId = 16,
                            ServiceId = 3
                        },
                        new
                        {
                            SupplierId = 17,
                            ServiceId = 3
                        },
                        new
                        {
                            SupplierId = 17,
                            ServiceId = 4
                        },
                        new
                        {
                            SupplierId = 17,
                            ServiceId = 6
                        },
                        new
                        {
                            SupplierId = 18,
                            ServiceId = 7
                        },
                        new
                        {
                            SupplierId = 19,
                            ServiceId = 7
                        },
                        new
                        {
                            SupplierId = 20,
                            ServiceId = 6
                        },
                        new
                        {
                            SupplierId = 21,
                            ServiceId = 6
                        },
                        new
                        {
                            SupplierId = 22,
                            ServiceId = 6
                        });
                });

            modelBuilder.Entity("NetPay.Data.Models.Expense", b =>
                {
                    b.HasOne("NetPay.Data.Models.Household", "Household")
                        .WithMany("Expenses")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetPay.Data.Models.Service", "Service")
                        .WithMany("Expenses")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("NetPay.Data.Models.SupplierService", b =>
                {
                    b.HasOne("NetPay.Data.Models.Service", "Service")
                        .WithMany("SuppliersServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetPay.Data.Models.Supplier", "Supplier")
                        .WithMany("SuppliersServices")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("NetPay.Data.Models.Household", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("NetPay.Data.Models.Service", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("SuppliersServices");
                });

            modelBuilder.Entity("NetPay.Data.Models.Supplier", b =>
                {
                    b.Navigation("SuppliersServices");
                });
#pragma warning restore 612, 618
        }
    }
}
