--12.Set Unique Field
ALTER TABLE [Users]
DROP CONSTRAINT PK_Users

ALTER TABLE [Users]
ADD CONSTRAINT PK_Users PRIMARY KEY(Id)

ALTER TABLE [Users]
ADD CONSTRAINT CHK_UsernameIsAtLeast3Symbols CHECK(LEN(Username) >= 3)